# This is the project file for the automated build system travis (travis-ci.com).
matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
    - os: osx

language: c

compiler: gcc

addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - libglew-dev
      - libhidapi-dev
      - libsdl2-dev
      - ninja-build

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew hidapi sdl2 cmake ninja; fi

install: true # skip install step

script: cmake . -G Ninja && ninja
