# This is the project file for the automated build system travis (travis-ci.com).
matrix:
  include:
    - os: linux
      sudo: false
      dist: trusty
    - os: osx

language: c

compiler: gcc

addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - libglew-dev
      - libhidapi-dev
      - libsdl2-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew hidapi ninja sdl2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv global system 3.6; fi
  - pip3 install meson

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -o ninja-linux.zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unzip ninja-linux.zip; fi

before_script:
  - export PATH="${PATH}:${PWD}"

script:
  - meson builddir -Dexamples=simple,opengl
  - ninja -C builddir
